disabled = false
languageCode = "ja"
languageName = "æ—¥æœ¬èª"
weight = 3
title = "danicat.dev"

[params]
  displayName = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006å¹´1æœˆ2æ—¥"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "ãƒ€ãƒ‹ã‚¨ãƒ©ãƒ»ãƒšãƒˆãƒ«ã‚¶ãƒ¬ã‚¯ã®å€‹äººãƒ–ãƒ­ã‚°"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "ãƒ€ãƒ‹ã‚¨ãƒ©ãƒ»ãƒšãƒˆãƒ«ã‚¶ãƒ¬ã‚¯"
  email = "daniela@danicat.dev"
  image = "chibi-dani.png"
  imageQuality = 96
  headline = "ãƒ†ã‚¯ãƒãƒ­ã‚¸ã‚¹ãƒˆã€ã‚²ãƒ¼ãƒãƒ¼ã€çŒ«å¥½ã"
  bio = "Googleã®ãƒ‡ãƒ™ãƒ­ãƒƒãƒ‘ãƒ¼ãƒªãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³ã‚ºã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢"
  links = [
#   { email = "mailto:daniela@danicat.dev" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
     { bluesky = "https://bsky.app/profile/danicat83.bsky.social" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/danicat" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/danicat83" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/petruzalek" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
    { x-twitter = "https://twitter.com/danicat83" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
    { ko-fi = "https://ko-fi.com/danicat" },
#     { codeberg = "https://codeberg.org/username"},
  ]
